spring:
  main:
    banner-mode: off
  application:
    name: spring-database
  datasource:
    url: jdbc:postgresql://localhost:5432/cities
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  springdoc:
    swagger-ui:
      path: /swagger-ui.html